version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

# docker-compose up --build
# docker-compose down
# docker-compose build --no-cache
# docker-compose up --build --force-recreate