spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/wee
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

#    sql:
#      init:
#        mode: never # always

    jpa:
      hibernate:
        ddl-auto: none # create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml